"""HS 2-digit chapter names (UN Comtrade returns codes only)."""

from __future__ import annotations

# German (original UI language).
HS2_NAMES_DE: dict[str, str] = {
    '01': 'Lebende Tiere', '02': 'Fleisch', '03': 'Fisch & Meeresfrüchte',
    '04': 'Milch, Eier, Honig', '05': 'Tierische Erzeugnisse', '06': 'Pflanzen & Blumen',
    '07': 'Gemüse', '08': 'Früchte & Nüsse', '09': 'Kaffee, Tee, Gewürze',
    '10': 'Getreide', '11': 'Mehl & Malz', '12': 'Ölsaaten',
    '13': 'Gummen & Harze', '14': 'Pflanzl. Flechtstoffe', '15': 'Fette & Öle',
    '16': 'Fleisch-/Fischwaren', '17': 'Zucker & Süßwaren', '18': 'Kakao & Schokolade',
    '19': 'Backwaren', '20': 'Gemüse-/Obstwaren', '21': 'Lebensmittelzubereitungen',
    '22': 'Getränke & Spirituosen', '23': 'Futtermittel', '24': 'Tabak',
    '25': 'Salz, Steine, Gips', '26': 'Erze & Schlacken', '27': 'Mineralöl, Gas & Brennstoffe',
    '28': 'Anorgan. Chemikalien', '29': 'Organ. Chemikalien', '30': 'Pharmazeutika',
    '31': 'Düngemittel', '32': 'Farb- & Gerbstoffe', '33': 'Kosmetik & Parfüm',
    '34': 'Seifen & Waschmittel', '35': 'Eiweiße & Klebstoffe', '36': 'Sprengstoffe',
    '37': 'Fotochemie', '38': 'Sonstige Chemie', '39': 'Kunststoffe',
    '40': 'Kautschuk & Gummi', '41': 'Häute & Leder', '42': 'Lederwaren & Taschen',
    '43': 'Pelze', '44': 'Holz & Holzwaren', '45': 'Kork',
    '46': 'Flecht- & Korbwaren', '47': 'Zellstoff', '48': 'Papier & Pappe',
    '49': 'Bücher & Drucke', '50': 'Seide', '51': 'Wolle',
    '52': 'Baumwolle', '53': 'Pflanzl. Spinnstoffe', '54': 'Synthetikfasern (Filament)',
    '55': 'Synthetikfasern (Spinn)', '56': 'Watte, Filz, Vliese', '57': 'Teppiche',
    '58': 'Spezialgewebe', '59': 'Technische Textilien', '60': 'Gewirke & Gestricke',
    '61': 'Bekleidung (gewirkt)', '62': 'Bekleidung (gewebt)', '63': 'Heimtextilien',
    '64': 'Schuhe', '65': 'Kopfbedeckungen', '66': 'Schirme',
    '67': 'Federn & Kunstblumen', '68': 'Steinwaren & Zement', '69': 'Keramik',
    '70': 'Glas & Glaswaren', '71': 'Edelsteine & Schmuck', '72': 'Eisen & Stahl',
    '73': 'Eisen-/Stahlwaren', '74': 'Kupfer', '75': 'Nickel',
    '76': 'Aluminium', '78': 'Blei', '79': 'Zink',
    '80': 'Zinn', '81': 'Andere unedle Metalle', '82': 'Werkzeuge & Besteck',
    '83': 'Metallwaren', '84': 'Maschinen & Geräte', '85': 'Elektrotechnik & Elektronik',
    '86': 'Schienenfahrzeuge', '87': 'Fahrzeuge (Kfz)', '88': 'Luftfahrzeuge',
    '89': 'Schiffe & Boote', '90': 'Optik & Messtechnik', '91': 'Uhren',
    '92': 'Musikinstrumente', '93': 'Waffen & Munition', '94': 'Möbel & Beleuchtung',
    '95': 'Spielzeug & Sport', '96': 'Diverse Waren', '97': 'Kunst & Antiquitäten',
    '99': 'Sonstiges / k.A.',
}

# English (the app's default language).
HS2_NAMES_EN: dict[str, str] = {
    '01': 'Live animals', '02': 'Meat', '03': 'Fish & seafood',
    '04': 'Dairy, eggs, honey', '05': 'Animal products', '06': 'Plants & flowers',
    '07': 'Vegetables', '08': 'Fruit & nuts', '09': 'Coffee, tea, spices',
    '10': 'Cereals', '11': 'Flour & malt', '12': 'Oil seeds',
    '13': 'Gums & resins', '14': 'Vegetable plaiting materials', '15': 'Fats & oils',
    '16': 'Prepared meat/fish', '17': 'Sugar & confectionery', '18': 'Cocoa & chocolate',
    '19': 'Bakery products', '20': 'Prepared vegetables/fruit', '21': 'Food preparations',
    '22': 'Beverages & spirits', '23': 'Animal feed', '24': 'Tobacco',
    '25': 'Salt, stone, plaster', '26': 'Ores & slag', '27': 'Mineral fuels, gas & oils',
    '28': 'Inorganic chemicals', '29': 'Organic chemicals', '30': 'Pharmaceuticals',
    '31': 'Fertilizers', '32': 'Dyes & pigments', '33': 'Cosmetics & perfume',
    '34': 'Soaps & detergents', '35': 'Proteins & adhesives', '36': 'Explosives',
    '37': 'Photo chemicals', '38': 'Other chemicals', '39': 'Plastics',
    '40': 'Rubber', '41': 'Hides & leather', '42': 'Leather goods & bags',
    '43': 'Fur', '44': 'Wood & wood products', '45': 'Cork',
    '46': 'Basketry & wickerwork', '47': 'Pulp', '48': 'Paper & cardboard',
    '49': 'Books & printed matter', '50': 'Silk', '51': 'Wool',
    '52': 'Cotton', '53': 'Vegetable textile fibers', '54': 'Synthetic filaments',
    '55': 'Synthetic staple fibers', '56': 'Wadding, felt, nonwovens', '57': 'Carpets',
    '58': 'Special woven fabrics', '59': 'Technical textiles', '60': 'Knitted fabrics',
    '61': 'Knitted apparel', '62': 'Woven apparel', '63': 'Home textiles',
    '64': 'Footwear', '65': 'Headgear', '66': 'Umbrellas',
    '67': 'Feathers & artificial flowers', '68': 'Stone & cement', '69': 'Ceramics',
    '70': 'Glass & glassware', '71': 'Gems & jewelry', '72': 'Iron & steel',
    '73': 'Iron/steel articles', '74': 'Copper', '75': 'Nickel',
    '76': 'Aluminum', '78': 'Lead', '79': 'Zinc',
    '80': 'Tin', '81': 'Other base metals', '82': 'Tools & cutlery',
    '83': 'Metal articles', '84': 'Machinery & appliances', '85': 'Electronics & electrical',
    '86': 'Rail vehicles', '87': 'Motor vehicles', '88': 'Aircraft',
    '89': 'Ships & boats', '90': 'Optics & measuring', '91': 'Watches',
    '92': 'Musical instruments', '93': 'Arms & ammunition', '94': 'Furniture & lighting',
    '95': 'Toys & sport', '96': 'Miscellaneous goods', '97': 'Art & antiques',
    '99': 'Other / n/a',
}
