"""Metric catalog: one entry per World Bank indicator shown on the map.

`higher_is_better` drives the colour-scale direction (None = neutral). Field names on
the wire (camelCase) are produced by `Metric.to_dict()`.
"""

from __future__ import annotations

from ..models import Metric

WORLD_BANK_METRICS: tuple[Metric, ...] = (
    Metric(
        id='gdp_per_capita',
        label='BIP pro Kopf',
        label_en='GDP per capita',
        short_label='BIP/Kopf',
        short_label_en='GDP/capita',
        unit='US$',
        unit_en='US$',
        description='BIP pro Einwohner, nominal in aktuellen US-Dollar (ohne Preisniveau-Ausgleich).',
        description_en='GDP per capita, nominal in current US dollars (no price-level adjustment).',
        domain='economy',
        format='currency',
        higher_is_better=True,
        indicator_code='NY.GDP.PCAP.CD',
    ),
    Metric(
        id='gdp_per_capita_ppp',
        label='BIP pro Kopf (KKP)',
        label_en='GDP per capita (PPP)',
        short_label='BIP/Kopf KKP',
        short_label_en='GDP/capita PPP',
        unit='Int$',
        unit_en='Int$',
        description='BIP pro Kopf zu Kaufkraftparität — gleicht das lokale Preisniveau aus, daher in ärmeren Ländern oft ein Vielfaches des nominalen Werts.',
        description_en='GDP per capita at purchasing power parity — evens out local price levels, so often a multiple of the nominal figure in poorer countries.',
        domain='economy',
        format='currency',
        higher_is_better=True,
        indicator_code='NY.GDP.PCAP.PP.CD',
    ),
    Metric(
        id='gdp_total',
        label='BIP gesamt',
        label_en='Total GDP',
        short_label='BIP',
        short_label_en='GDP',
        unit='US$',
        unit_en='US$',
        description='Bruttoinlandsprodukt insgesamt, aktuelle US-Dollar.',
        description_en='Gross domestic product, current US dollars.',
        domain='economy',
        format='currency',
        higher_is_better=True,
        indicator_code='NY.GDP.MKTP.CD',
    ),
    Metric(
        id='population',
        label='Bevölkerung',
        label_en='Population',
        short_label='Bevölkerung',
        short_label_en='Population',
        unit='Menschen',
        unit_en='people',
        description='Gesamtbevölkerung (Mitte des Jahres).',
        description_en='Total population (mid-year estimate).',
        domain='demographics',
        format='number',
        higher_is_better=None,
        indicator_code='SP.POP.TOTL',
    ),
    Metric(
        id='life_expectancy',
        label='Lebenserwartung',
        label_en='Life expectancy',
        short_label='Lebenserwartung',
        short_label_en='Life expectancy',
        unit='Jahre',
        unit_en='years',
        description='Lebenserwartung bei Geburt, gesamt.',
        description_en='Life expectancy at birth, all sexes.',
        domain='health',
        format='years',
        higher_is_better=True,
        indicator_code='SP.DYN.LE00.IN',
    ),
    Metric(
        id='gini',
        label='Gini-Index (Ungleichheit)',
        label_en='Gini index (inequality)',
        short_label='Gini',
        short_label_en='Gini',
        unit='Index 0–100',
        unit_en='Index 0–100',
        description='Einkommensungleichheit; 0 = perfekt gleich, 100 = maximal ungleich.',
        description_en='Income inequality; 0 = perfectly equal, 100 = maximally unequal.',
        domain='social',
        format='index',
        higher_is_better=False,
        indicator_code='SI.POV.GINI',
    ),
    Metric(
        id='health_expenditure_gdp',
        label='Gesundheitsausgaben',
        label_en='Health expenditure',
        short_label='Gesundheit',
        short_label_en='Health',
        unit='% des BIP',
        unit_en='% of GDP',
        description='Laufende Gesundheitsausgaben als Anteil am BIP.',
        description_en='Current health expenditure as a share of GDP.',
        domain='health',
        format='percent',
        higher_is_better=None,
        indicator_code='SH.XPD.CHEX.GD.ZS',
    ),
    Metric(
        id='unemployment',
        label='Arbeitslosenquote',
        label_en='Unemployment rate',
        short_label='Arbeitslosigkeit',
        short_label_en='Unemployment',
        unit='% der Erwerbspersonen',
        unit_en='% of labor force',
        description='Arbeitslosigkeit als Anteil der Erwerbsbevölkerung (ILO-Schätzung).',
        description_en='Unemployment as a share of the labor force (ILO estimate).',
        domain='economy',
        format='percent',
        higher_is_better=False,
        indicator_code='SL.UEM.TOTL.ZS',
    ),
    Metric(
        id='inflation',
        label='Inflation',
        label_en='Inflation',
        short_label='Inflation',
        short_label_en='Inflation',
        unit='% pro Jahr',
        unit_en='% per year',
        description='Verbraucherpreisinflation, jährliche Veränderung.',
        description_en='Consumer price inflation, annual change.',
        domain='economy',
        format='percent',
        higher_is_better=None,
        indicator_code='FP.CPI.TOTL.ZG',
    ),
    Metric(
        id='gdp_growth',
        label='BIP-Wachstum',
        label_en='GDP growth',
        short_label='Wachstum',
        short_label_en='Growth',
        unit='% pro Jahr',
        unit_en='% per year',
        description='Reales jährliches Wachstum des Bruttoinlandsprodukts.',
        description_en='Real annual growth of gross domestic product.',
        domain='economy',
        format='percent',
        higher_is_better=True,
        indicator_code='NY.GDP.MKTP.KD.ZG',
    ),
    Metric(
        id='exports_gdp',
        label='Exporte (Anteil am BIP)',
        label_en='Exports (% of GDP)',
        short_label='Exporte',
        short_label_en='Exports',
        unit='% des BIP',
        unit_en='% of GDP',
        description='Exporte von Waren und Dienstleistungen als Anteil am BIP.',
        description_en='Exports of goods and services as a share of GDP.',
        domain='economy',
        format='percent',
        higher_is_better=None,
        indicator_code='NE.EXP.GNFS.ZS',
    ),
    Metric(
        id='poverty',
        label='Extreme Armut',
        label_en='Extreme poverty',
        short_label='Armut',
        short_label_en='Poverty',
        unit='% der Bevölkerung',
        unit_en='% of population',
        description='Anteil der Bevölkerung unter 2,15 $/Tag (KKP 2017).',
        description_en='Share of the population living below 2.15 US$ per day (2017 PPP).',
        domain='social',
        format='percent',
        higher_is_better=False,
        indicator_code='SI.POV.DDAY',
    ),
    Metric(
        id='education_expenditure',
        label='Bildungsausgaben',
        label_en='Education expenditure',
        short_label='Bildung',
        short_label_en='Education',
        unit='% des BIP',
        unit_en='% of GDP',
        description='Staatliche Bildungsausgaben als Anteil am BIP.',
        description_en='Government education expenditure as a share of GDP.',
        domain='social',
        format='percent',
        higher_is_better=None,
        indicator_code='SE.XPD.TOTL.GD.ZS',
    ),
    Metric(
        id='fertility',
        label='Geburtenrate',
        label_en='Fertility rate',
        short_label='Geburtenrate',
        short_label_en='Fertility',
        unit='Kinder/Frau',
        unit_en='children/woman',
        description='Zusammengefasste Geburtenziffer (Kinder pro Frau).',
        description_en='Total fertility rate (children per woman).',
        domain='health',
        format='number',
        higher_is_better=None,
        indicator_code='SP.DYN.TFRT.IN',
    ),
    Metric(
        id='urban_population',
        label='Stadtbevölkerung',
        label_en='Urban population',
        short_label='Urbanisierung',
        short_label_en='Urbanization',
        unit='% der Bevölkerung',
        unit_en='% of population',
        description='Anteil der Bevölkerung, der in Städten lebt.',
        description_en='Share of the population living in cities.',
        domain='demographics',
        format='percent',
        higher_is_better=None,
        indicator_code='SP.URB.TOTL.IN.ZS',
    ),
    Metric(
        id='co2_per_capita',
        label='CO₂ pro Kopf',
        label_en='Urban population',
        short_label='CO₂/Kopf',
        short_label_en='Urbanization',
        unit='t pro Jahr',
        unit_en='% of population',
        description='Energiebedingte CO₂-Emissionen pro Kopf (ohne Landnutzung).',
        description_en='Share of the population living in cities.',
        domain='environment',
        format='number',
        higher_is_better=False,
        indicator_code='EN.GHG.CO2.PC.CE.AR5',
    ),
    Metric(
        id='internet_users',
        label='Internetnutzer',
        label_en='Internet users',
        short_label='Internet',
        short_label_en='Internet',
        unit='% der Bevölkerung',
        unit_en='% of population',
        description='Anteil der Bevölkerung mit Internetzugang.',
        description_en='Share of the population with internet access.',
        domain='infrastructure',
        format='percent',
        higher_is_better=True,
        indicator_code='IT.NET.USER.ZS',
    ),
    Metric(
        id='electricity_access',
        label='Stromzugang',
        label_en='Electricity access',
        short_label='Strom',
        short_label_en='Electricity',
        unit='% der Bevölkerung',
        unit_en='% of population',
        description='Anteil der Bevölkerung mit Zugang zu Elektrizität.',
        description_en='Share of the population with access to electricity.',
        domain='infrastructure',
        format='percent',
        higher_is_better=True,
        indicator_code='EG.ELC.ACCS.ZS',
    ),
    Metric(
        id='mobile_subscriptions',
        label='Mobilfunkverträge',
        label_en='Mobile subscriptions',
        short_label='Mobilfunk',
        short_label_en='Mobile',
        unit='pro 100 Einw.',
        unit_en='per 100 people',
        description='Mobilfunkverträge je 100 Einwohner.',
        description_en='Mobile cellular subscriptions per 100 inhabitants.',
        domain='infrastructure',
        format='number',
        higher_is_better=None,
        indicator_code='IT.CEL.SETS.P2',
    ),
)
